databases:
  - name: kms
    databaseName: kms
    user: kms

services:
  - type: web
    name: kms
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn kms.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kms
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4