# Generated by Django 4.1.3 on 2022-12-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
