# Generated by Django 4.1.3 on 2022-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0002_alter_subject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
